export const PERSPECTIVE = 1100
export const SIDE_WIDTH = 90
export const DEFAULT_TRANSITION_TIME = 396
export const DECONSTRUCT_TRANSITION_TIME = 99
export const DECONSTRUCT_MOVES_COUNT = 40
export const DISPLAY_WIDTH = 333
